server:
  port: 8080

spring:
  redis:
    host: 47.105.165.183
    port: 6379

  elasticsearch:
    host: localhost
    port: 9200
    scheme: http
    socket-timout: 30000
    connection-timeout: 1500
    read-timeout: 10000
    connection-request-timout: 500
    max-connection-num: 100
    max-connection-per-route: 100
#  security:
#    user:
#      name: admin
#      password: 123456
